- gym_robotics/__init__.py
Add deprecation warning to install `gymnasium_robotics` instead of `gym_robotics`. `gymnasium_robotics` will be the new name of the package since the dependency on `gym` will be migrated to `gymnasium`.
> Add depreation warning for gym_robotics package

- .pre-commit-config.yaml
#25 is failing due to non relevant `codespell` errors in the pre-commit check. This PR excludes `.svg` files.
> Remove .svg files from pre-commit codespell check

- gymnasium_robotics/envs/fetch_env.py
- gymnasium_robotics/envs/hand_env.py
- gymnasium_robotics/envs/robot_env.py
- tests/test_envs.py
This PR updates the rendering API of the mujoco environments to the new `MujocoRenderer` class in Gymnasium v0.27.0
https://github.com/Farama-Foundation/Gymnasium/pull/112
> Update to refactored mujoco renderer in Gymnasium v0.27.0

- docs/envs/hand_touch/index.md
Just a typo fix
```
import gymnasium
>>> env = gymnasium.make('HandManipulateEgg_BooleanTouchSensor-v1') #does not work
>>> env = gymnasium.make('HandManipulateEgg_BooleanTouchSensors-v1') #works
```
> DOC typo fix

- gymnasium_robotics/__init__.py
- gymnasium_robotics/envs/hand/manipulate.py
Fix redundant registration of `PointMaze_Open-v3` environment.
> Remove redundant environment registration

- .pre-commit-config.yaml
- gymnasium_robotics/__init__.py
- gymnasium_robotics/envs/adroit_hand/door.py
- gymnasium_robotics/envs/adroit_hand/hammer.py
- gymnasium_robotics/envs/adroit_hand/pen.py
- gymnasium_robotics/envs/adroit_hand/relocate.py
- Added docstrings for adroit hand environments.
- Bump adroit hand to v1. v0 referenced to the D4RL environments
- Skip pydocstyle pre-commit. TODO in future PR
> Docstrings for Adroit hand

- pyproject.toml
The package name in `pyproject.toml` for the configuration `setuptools.packages.find` is set incorrectly to `robotics` instead of `gymnasium_robotics`. Due to this the package can't be imported. 
As specified in https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html, there is no need to add this configuration since setuptools will automatically detect the package directory and name.
This PR removes `setuptools.packages.find` from `pyproject.toml`
> Solve package name import issue

- pyproject.toml
There is no reason for it to be disabled in this repo, no errors are generated
> enable `pyright.reportOptionalMemberAccess`

- docs/envs/MaMuJoCo/index.md
- docs/envs/MaMuJoCo/ma_ant.md
- docs/envs/MaMuJoCo/ma_coupled_half_cheetah.md
- docs/envs/MaMuJoCo/ma_half_cheetah.md
- docs/envs/MaMuJoCo/ma_hopper.md
- docs/envs/MaMuJoCo/ma_humanoid.md
- docs/envs/MaMuJoCo/ma_humanoid_standup.md
- docs/envs/MaMuJoCo/ma_pusher.md
- docs/envs/MaMuJoCo/ma_reacher.md
- docs/envs/MaMuJoCo/ma_single.md
- docs/envs/MaMuJoCo/ma_swimmer.md
- docs/envs/MaMuJoCo/ma_walker2d.md
Some documentation updates:
* Note about installing `mamujoco` from source in current `1.2.0` `Gymnasium-Robotics` release. #95
* Remove tabs from environments in webpage
> MaMuJoCo documentation updates

- gymnasium_robotics/envs/fetch/fetch_env.py
Rendering the fetch environment raises an error, that `get_gripper_xpos` is not defined.
Looking into the code, I noticed that the leading underscore is missing, changing it from `self.get_gripper_xpos` to `self._get_gripper_xpos` resolved the issue.
> Add missing underscore to fix rendering

- gymnasium_robotics/envs/maze/maze.py
When we modify the goal position of maze_map, the visualization does not change at all, while the goal in the code was right. I found the position of the goal in visualization only updated when `goal-cell` was passed in `options`.
```
import gymnasium as gym
example_map = [
[1, 1, 1, 1, 1],
[1, "r", 0, "g", 1],
[1, 1, 1, 0, 1]
]
env = gym.make('AntMaze_UMaze-v3', render_mode='human', maze_map=example_map)
```
| Before | After |
| ------ | ----- |
| <img width="1002" alt="image" src="https://user-images.githubusercontent.com/17773634/217991144-25e72535-486c-447a-9a01-17ffee21d6e4.png"> | <img width="1072" alt="image" src="https://user-images.githubusercontent.com/17773634/217991253-f2d3ba8e-ff6b-4105-b71a-fb1beb296bc0.png"> |
> update the position of the goal every reset in AntMaze environment

- gymnasium_robotics/envs/franka_kitchen/franka_env.py
The actions for the `FrankaKitchen-v1` with joint position control action space are not set to the correct range before stepping. 
Fixes #116 
> Fix issue 116

- gymnasium_robotics/envs/adroit_hand/adroit_door.py
- gymnasium_robotics/envs/adroit_hand/adroit_hammer.py
- gymnasium_robotics/envs/adroit_hand/adroit_pen.py
- gymnasium_robotics/envs/adroit_hand/adroit_relocate.py
- pyproject.toml
The previous version of d4rl sparse envs gave a small reward for almost solving the env, and a larger reward for completely solving it. This caused issues where agents tended to exploit the reward structure by staying in configurations where it could perpetually collect the small reward, resulting in a low success rate outright.
This sparsification results in the environment only giving a reward of 1.0 when the environment is solved, and a reward of 0.0 otherwise.
> Resparsify adroit hand envs

- gymnasium_robotics/envs/adroit_hand/adroit_door.py
- gymnasium_robotics/envs/adroit_hand/adroit_hammer.py
- gymnasium_robotics/envs/adroit_hand/adroit_pen.py
- gymnasium_robotics/envs/adroit_hand/adroit_relocate.py
Pass the `initial_state_dict` dictionary through the `options` argument in `reset()` in the `AdroitHand` environments. 
For good practice purposes `options` dictionary should be the default to specify any additional information that conditions how the environment is reset. https://gymnasium.farama.org/api/env/#gymnasium.Env.reset
> Adroit reset add `initial_state_dict` to options

- gymnasium_robotics/utils/mujoco_utils.py
Fixes #133 where getter functions for qpos / qvel return views instead of copies of the simulator data structure. If a user modifies these views, they will modify the simulator data as well, which is likely unintentional.
Note: I did not see a `CONTRIBUTING.md` in the main branch, so I was unable to do the checklist below. Please let me know how to proceed there.
> make getter functions for qpos / qvel return copies

- pyproject.toml
Set PZ to 1.22.3
the API changes in 1.22.4 make it incompatible with `MaMuJoCo`
https://github.com/Farama-Foundation/PettingZoo/releases
I do not plan to port it to 1.22.4 (the release have been yanked)
I will port it to 1.22.5 once that comes out
> set `PettingZoo` dependency to 1.22.3

- pyproject.toml
works fine with `numpy==1.24.3`
> uncap `numpy` version

- gymnasium_robotics/envs/maze/maze.py
Fix `compute_reward` function can not compute reward for batch input in `AntMaze` environment.
> bug fix: compute_reward for batch input

- .github/workflows/build.yml
- .pre-commit-config.yaml
- README.md
- pyproject.toml
`python 3.7 `is EOL, and therefore we drop support (following gymnasium)
> remove python 3.7 support

- gymnasium_robotics/envs/franka_kitchen/franka_env.py
- gymnasium_robotics/envs/franka_kitchen/utils.py
- pyproject.toml
1. Fix CI issue with `mujoco_py` by specifying the `cython` version. Same issue as in Gymnasium, fixed in https://github.com/Farama-Foundation/Gymnasium/pull/616.
2. Close `franka_config.xml` after opening.
3. Fix Deprecation Warning from `numpy==1.25.0` in Franka environment
> Fix CI for Gymnasium v0.29.0

- gymnasium_robotics/envs/maze/maze.py
- gymnasium_robotics/envs/maze/maze_v4.py
- tests/envs/maze/test_point_maze.py
This PR fixes an assertion error that arises when a specific `goal_cell` or `reset_cell` are passed as options in the `point_maze` env. 
Fixes #163 
`pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
> Fix list index error when goal_cell and reset_cell are passed as options in PointMaze env

- gymnasium_robotics/envs/maze/ant_maze_v4.py
- gymnasium_robotics/envs/maze/maze_v4.py
- gymnasium_robotics/envs/maze/point_maze.py
This PR adds the `reset_target` boolean argument to v4 antmaze environments. If this argument is set to `True` and `continuing_task` is also `True`, the goal won't be re-generated to another location when reached by the agent. If `False` and `continuing_task` still  equals `True`, then another goal location will be generated instead of terminating/truncating the episode when the ant reaches a goal.
> Add  reset_target argument to antmaze environments

- gymnasium_robotics/envs/maze/ant_maze_v4.py
- gymnasium_robotics/envs/maze/maze_v4.py
- gymnasium_robotics/envs/maze/point_maze.py
This PR makes the following updates to the maze environments (`pointmaze` and `antmaze`):
- Default `reset_target` to `False`.
- When there are no goals ("g") or reset ("r") cells provided in the `maze_map` structure, the environment will select these cells at random from the empty cells ("0") when reset. 
- Allow serialization of the `reset_target` argument with EzPickle
> Update Maze environments

- docs/_scripts/gen_envs_display.py
Remove versioning from file names.
Removes the display in the middle from the docs:
> Fix gen_envs_display.py in docs 

- gymnasium_robotics/envs/maze/maze.py
- gymnasium_robotics/envs/maze/maze_v4.py
This PR fixes the comment in this previous PR https://github.com/Farama-Foundation/Gymnasium-Robotics/issues/163#issuecomment-1675839059
The elements of "goal_cell" and "reset_cell" need to be inverted for the assertions since they represent the `(i,j)` cell in the maze map list of lists structure as specified in the [docs](https://robotics.farama.org/envs/maze/point_maze/#starting-state).
The changes are made in both `maze.py` and `maze_v4.py`
> [Bug Fix] Correct assertions in Maze environment reset

- gymnasium_robotics/envs/maze/maze_v4.py
fixes issue https://github.com/Farama-Foundation/Gymnasium-Robotics/issues/184 by assigning a unique name to all temporary asset files 
> randomize maze environments temporary `xml` file name

- pyproject.toml
> limit `mujoco<3.0`

- gymnasium_robotics/__init__.py
Registers the `PointMaze_Open_Diverse_GR` environment. 
Fixes #194 
> Register PointMaze_Open_Diverse_GR

- gymnasium_robotics/envs/adroit_hand/adroit_door.py
- gymnasium_robotics/envs/adroit_hand/adroit_hammer.py
- gymnasium_robotics/envs/adroit_hand/adroit_pen.py
- gymnasium_robotics/envs/adroit_hand/adroit_relocate.py
Replaces `True if Statement else False` with `Statement`
```py
>>> True if True else False
True
>>> True if False else False
False
```
> [adroit ]Minor Cleanup: assignment of `goal_achieved`

- .pre-commit-config.yaml
From now on, since `gymnasium` pins `pyright,` we shall follow so
> pin `pyright==1.1.347` (match gymnasium)

- docs/content/multi-goal_api.md
- docs/envs/franka_kitchen/index.md
- docs/envs/shadow_dexterous_hand/index.md
- docs/index.md
- gymnasium_robotics/__init__.py
- gymnasium_robotics/envs/adroit_hand/adroit_door.py
- gymnasium_robotics/envs/adroit_hand/adroit_hammer.py
- gymnasium_robotics/envs/adroit_hand/adroit_pen.py
- gymnasium_robotics/envs/adroit_hand/adroit_relocate.py
- gymnasium_robotics/envs/fetch/pick_and_place.py
- gymnasium_robotics/envs/fetch/push.py
- gymnasium_robotics/envs/fetch/reach.py
- gymnasium_robotics/envs/fetch/slide.py
- gymnasium_robotics/envs/franka_kitchen/kitchen_env.py
- gymnasium_robotics/envs/maze/ant_maze.py
- gymnasium_robotics/envs/maze/ant_maze_v4.py
- gymnasium_robotics/envs/maze/point_maze.py
- gymnasium_robotics/envs/multiagent_mujoco/mujoco_multi.py
- gymnasium_robotics/envs/shadow_dexterous_hand/manipulate_block.py
- gymnasium_robotics/envs/shadow_dexterous_hand/manipulate_egg.py
- gymnasium_robotics/envs/shadow_dexterous_hand/manipulate_pen.py
- pyproject.toml
- tests/envs/franka_kitchen/test_kitchen_env.py
- tests/envs/hand/test_manipulate.py
- tests/envs/hand/test_manipulate_touch_sensors.py
- tests/envs/hand/test_reach.py
- tests/test_envs.py
- Updates `import` to work without the removed plugin system (and updates the DOC)
- pin `gymnasium==1.0.0a1`
- update tests to not use the removed `env.get_attr()`
- fix bounds check string https://github.com/Farama-Foundation/Gymnasium/pull/634
- relax `MuJuCo` version requirements
- added `MazeEnv.model` and `MazeEnv.data` properties (useful for testing)
>  `gymnasium==1.0` support

- gymnasium_robotics/utils/mujoco_utils.py
Added asserts for calls to mj_id2name calls. In case the resource is not available in the model definition the call returns `-1`. After these calls this case is not handled as an error and values for the wrong joint, site, or body are returned.
This change increases the reusability of mujoco_utils and is especially helpful when creating or customizing mujoco environments.
(not necessary here)
(not necessary here)
(not necessary here)
> Add asserts for `mj_id2name` calls in `mujoco_utils`

- README.md
fixes https://github.com/Farama-Foundation/Gymnasium-Robotics/issues/222
> fix readme implying MaMuJoCo is part of D4RL environments.

- tests/test_envs.py
The tests were disabled due to the removal of gymnasium's plugin system
> re-enable disabled  `test_envs.py` (`mujoco` only)

- gymnasium_robotics/envs/robot_env.py
Gymnasium 1.0.0 added the width and height parameters to the initialization method of the `MujocoRenderer` class. If no values are passed in, they default to None and this causes rendering to fail when the `render_mode` is set to `rgb_array` (at least for onscreen rendering). This fix passes the height and width parameters in the `BaseRobotEnv` class to the `MujocoRenderer` in `robot_env.py`, resolving the issue. 
Fixes #235
> Fix rendering bug by setting frame height and width

- gymnasium_robotics/envs/maze/point_maze.py
Fixed error in the reward description of the PointMaze env.
> Fixed reward description of `PointMaze` dense environments

- gymnasium_robotics/envs/assets/kitchen_franka/kitchen_assets/item_assets/kettle_asset.xml
There's a missing <default> tag in kettle_asset.xml. This will bring errors in the latest version of MuJoCo (>3.16). I have validated that this change does not change the behavior of the environment for older versions of mujoco (3.1.6, 3.0.1). However, the behavior in MuJoCo version (<3.0, e.g. 2.1.5) remains to be checked (if needed).
Related issues $ temp fixes includes: 
https://github.com/Farama-Foundation/D4RL/issues/236#issue-2420593982
https://github.com/CleanDiffuserTeam/CleanDiffuser/pull/24
https://github.com/Farama-Foundation/D4RL/pull/238#issue-2600047899
This behavior aligns with other assets descriptions in kitchen. For example, in microwave:
```xml
<default>
<default class="microwave">
<joint damping="2" frictionloss="2" …
```
> Fix bugs in kettle_asset.xml to ensure compatibility with the latest MuJoCo versions

- gymnasium_robotics/__init__.py
- gymnasium_robotics/envs/fetch/fetch_env.py
- gymnasium_robotics/envs/fetch/pick_and_place.py
- gymnasium_robotics/envs/fetch/push.py
- gymnasium_robotics/envs/fetch/reach.py
- gymnasium_robotics/envs/fetch/slide.py
- gymnasium_robotics/envs/robot_env.py
- gymnasium_robotics/envs/shadow_dexterous_hand/reach.py
- tests/envs/hand/test_reach.py
- tests/test_envs.py
Adding back the lines described in #251 to fix the initial state changes introduced in `gymnasium-robotics>=1.3.0, <=1.3.1`.
Adding back removed data setting lines removed in 1.3.0. Following Gymnasium's `mujoco_env.py` workflow, the procedure to reset an environment for Fetch and Robotic environments are:
1. `mujoco._mj_resetData(self.model, self.data)`
2. Update `self.data` to the saved initial data.
3. `mujoco.mf_forward(self.model, self.data)`
The second step changes for different environments. Changes in 1.3.0 removed the second step. The third step is called in `set_state()` in `mujoco_env.py`. 
Update impacted `Fetch` environments to V4 and `HandReach` environment to V3. Other Shadow Dexterous Hand environments are not impacted since they inherit `MujocoManipulateEnv` which has a …
> Fixes Fetch and Robotic environments initial state issues in 1.3.0

- README.md
Clicking the logo image on the documentation launches the website in another tab
The logo has been updated to be clickable and opens the Gymnasium-Robotics website in a new tab when clicked. This change improves navigation by allowing users to visit the website without leaving the current page.
> Make logo image in `README.md` link to documentation

- gymnasium_robotics/envs/assets/kitchen_franka/kitchen_assets/item_assets/oven_asset.xml
The mujoco xml docs state that "All [rgba] components should be in the range [0 1]."
https://mujoco.readthedocs.io/en/stable/XMLreference.html#asset-material
MuJoCo's parser clearly let's this through. But it seems that mine is a little more strict.
I checked with the original author @abhishekunique, and he confirmed that it's just a bug (from his original work), and that it should be fixed.
Related to https://github.com/RobotLocomotion/drake/pull/22445.
> Fix rgba value in `oven_asset.xml` to be in `[0,1]`

- .pre-commit-config.yaml
- docs/_scripts/gen_mds.py
- gymnasium_robotics/__init__.py
- gymnasium_robotics/envs/franka_kitchen/utils.py
- gymnasium_robotics/envs/shadow_dexterous_hand/hand_env.py
- pyproject.toml
The website doc is failing due to the mujoco-py environment not having the docs here, as they are still part of gymnasium 
The gymnasium has errors for the mujoco-py environment; therefore, we overwrite them currently, which raises a warning. 
It's fixed by removing the gymnasium version and re-registering the environment.
> Fix website doc build and remove env overwrite warning
