Farama-Foundation/Gymnasium-Robotics

- gym_robotics/core.py
> Adopt `gym>=0.22` reset signature

- requirements.txt
- setup.py
> Use `gym>=0.22` as the core dependency

- docs/FetchPickAndPlace.md
- docs/FetchPush.md
- docs/FetchReach.md
- docs/FetchSlide.md
This is a basic documentation for the Fetch environments. 
See #11
> Fetch initial documentation

- .github/workflows/build.yml
- .github/workflows/pre-commit.yml
Following https://github.com/openai/gym/pull/3094, adds explicit permissions for the GitHub workflows for PRs.
- New feature (non-breaking change which adds functionality)
> Update security permissions for GitHub workflows

- setup.py
This PR adds the correct path  in `setup.py` to the entry points for the environment registration.
> Fix path to entry points

- README.md
> Fix typos and codestyle in the README

- docs/index.md
Remove citations in website homepage and add gymnasium example
> Update website homepage

- docs/index.md
Last PR #46 removed the webpage section. This PR adds them again.
> Fix homepage

- gymnasium_robotics/envs/hand/manipulate.py
- gymnasium_robotics/envs/hand/manipulate_touch_sensors.py
- gymnasium_robotics/envs/hand/reach.py
This just adds the missing links to the gifs.
> Add missing gif links

- docs/index.md
> Fix gif home page website

- tests/utils.py
Fix pyright Private Import Usage in pre-commit.
Fixes #58 
> Fix pyright issue #58

- requirements.txt
- setup.py
Pin numpy to <1.24.0 due to https://github.com/Farama-Foundation/Gymnasium/pull/221. For now this will allow for test to pass in the mean time. Gymnasium-robotics will wait until for next Gymnasium release >0.27 to bump numpy version
> Numpy<1.24.0

- .github/workflows/gh-pages.yml
- docs/envs/fetch/index.md
- docs/envs/hand/index.md
- docs/envs/hand_touch/index.md
- docs/requirements.txt
* remove unnecessary requirements
* change env toctrees to glob 
*  force python version in `gh-pages` workflow
> Small improvements to docs generation

- .pre-commit-config.yaml
- gymnasium_robotics/__init__.py
- gymnasium_robotics/core.py
- gymnasium_robotics/envs/__init__.py
- gymnasium_robotics/envs/fetch_env.py
- gymnasium_robotics/envs/hand/manipulate.py
- gymnasium_robotics/envs/hand_env.py
- gymnasium_robotics/envs/robot_env.py
- gymnasium_robotics/utils/mujoco_utils.py
- gymnasium_robotics/utils/rotations.py
- pyproject.toml
Add pydocstyle to pre-commit workflow with google convention. This PR will only add pydocstrings to `core.py`, `robot_env.py`, `hand_env.py`, and `fetch_env.py`. 
Docstrings for the other directories will be made in future PR's (`utils/`, `envs/hand`, `envs/fetch`)
#57 
> Pydocstyle

- .github/workflows/build.yml
- README.md
- docs/content/installation.md
- py.Dockerfile
- setup.py
- test_requirements.txt
Add Python 3.11 to the list of requirements and upgrade to latest working mujoco version >=2.3.1.post1
> Python 3.11 and mujoco >=2.3.1

- setup.py
The long description was removed in the setup.py to toml conversion, this PR adds it back
> Add back long description

- .github/workflows/gh-pages.yml
- requirements.txt
- test_requirements.txt
Remove `requirements.txt` and `test_requirements.txt` to only  use `pyproject.toml` for dependency install.
Also update documentation webpage build workflow.
> Remove requirements txt

- gymnasium_robotics/__init__.py
Bump to new 1.2.0 version with D4RL environments
> bump version 1.2.0

- README.md
- gymnasium_robotics/__init__.py
> README fix for PyPI description generation

- README.md
Fix Pypi error when generating new release.
> Add long description content type to setup.py

- .pre-commit-config.yaml
- pyproject.toml
We were talking about it on `Discord`
> (temp) make mamujoco requirement mandatory

- docs/conf.py
- docs/requirements.txt
`sphinx_github_changelog` requirement was missing.
> Add missing docs requirement and fix docs conf.py

- gymnasium_robotics/envs/multiagent_mujoco/mujoco_multi.py
https://github.com/Farama-Foundation/Gymnasium-Robotics/issues/131
- [NO] I have added tests that prove my fix is effective or that my feature works
> update render to also support zoo render api

- pyproject.toml
temp solution for https://github.com/deepmind/mujoco/issues/833
> pin `mujoco==2.3.3`

- pyproject.toml
Changes made in the last PettingZoo release `v1.23.0` require updates to `MaMujoco` environments. This PR pings PettingZoo dependency to `v1.22.3` while the environments are being updated.
> Ping PettingZoo v1.22.3

- gymnasium_robotics/envs/multiagent_mujoco/mujoco_multi.py
- pyproject.toml
- [] New feature (non-breaking change which adds functionality)
> update MaMuJoCo for PettingZoo 1.23 API

- docs/envs/MaMuJoCo/index.md
`pip install gymnasium_robotics==1.2.1` includes it now
> `MaMuJoCo` documentation, remove install from source instructions

- docs/requirements.txt
No need to impose a specific version.
> Update docs to Sphinx latest version

- gymnasium_robotics/envs/franka_kitchen/kitchen_env.py
- tests/envs/franka_kitchen/test_kitchen_env.py
This PR fixes issue #166 and adds a test to check for the completion items in the infos of `FrankaKitchen-v1`.
> Fix 166 and tests

- pyproject.toml
Revert https://github.com/Farama-Foundation/Gymnasium-Robotics/pull/143 to `mujoco>=2.3.3` as Gymnasium 0.29.1 fixes the following issue https://github.com/deepmind/mujoco/issues/833 
> Remove mujoco constraint version

- docs/conf.py
- docs/index.md
- docs/release_notes/index.md
This PR adds the "sphinx_github_changelog" extension.
> Fix changelog release notes in docs

- pyproject.toml
> Update pyproject.toml python version to 3.8

- .pre-commit-config.yaml
Not the latest version (the latest is `1.1.342`), but newer than what gymnasium uses, I will update once gymnasium also updates
> Update to `pyright==1.1.339`

- .github/PULL_REQUEST_TEMPLATE.md
> Update PULL_REQUEST_TEMPLATE.md to the latest version

- docs/envs/MaMuJoCo/ma_multiagentswimmer.md
> typo fix in ma_multiagentswimmer.md

- gymnasium_robotics/envs/robot_env.py
Fixed typo for the word "bindings"
> Fixed typo

- pyproject.toml
there are issues loading the franka model with mujoco==3.2.0
> limit `mujoco<=3.2.0`

- .github/workflows/build.yml
- README.md
- pyproject.toml
- tests/envs/hand/test_manipulate.py
- tests/envs/hand/test_reach.py
> add py3.12

- docs/envs/MaMuJoCo/index.md
> mamujoco v1 changelog remove duplicate entry

- docs/envs/MaMuJoCo/index.md
> mamujoco changelog update

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- tests/utils.py
> Use `pipx` for CI `pre-commit`

- .github/workflows/pre-commit.yml
- gymnasium_robotics/__init__.py
> Fix MazeAnt-v5 environments having incorect entry points

- .github/workflows/build.yml
- pyproject.toml
- tests/test_envs.py
> reenable mujoco-py tests

- README.md
- gymnasium_robotics/__init__.py
> version 1.3.1
